export const REQUEST_GROUP = 'REQUEST_GROUP';
export const REQUEST_GROUP_SUCCESS = 'REQUEST_GROUP_SUCCESS';
export const REQUEST_GROUP_ERROR = 'REQUEST_GROUP_ERROR';

export const ADD_GROUP = 'ADD_GROUP';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_ERROR = 'ADD_GROUP_ERROR';
